const {test,expect} = require('@playwright/test');
const {POManager}=require('../PageObjects/POManager');
import { faker } from '@faker-js/faker';
const testdata=JSON.parse( JSON.stringify(require('../TestData/signInPageTestData.json')));

test.beforeEach(async({page})=>{
    const poManager=new POManager(page);
    const signinPage=poManager.getSigninPage();
    await signinPage.navigate(testdata.url);
    await signinPage.enterEmail(testdata.adminusername);
    await signinPage.enterPassword(testdata.password);
    await signinPage.clickSignin();
    await expect(page).toHaveURL("https://skill-assist.ai/QapitolQA/dashboard");
    //await page.waitForTimeout(5000);
});
test('Test Onboarding Admin',async({page})=>{
    const poManager=new POManager(page);
    const adminDashBoard=poManager.getAdminDashBoard();
    const usermanagement= poManager.getUserManagementPage();
    await adminDashBoard.clickUserManagementModule();
    await usermanagement.clickOnboardingTab();
    const email=faker.internet.email();
    await usermanagement.enterEmail(email);
    const firstName=faker.person.firstName();
    await usermanagement.enterFirstName(firstName);
    const lastName=faker.person.lastName();
    await usermanagement.enterLastName(lastName);
    await usermanagement.selectRole(testdata.adminrole);
    await usermanagement.selectDepartment('Engineering');
    await usermanagement.enterPassword(testdata.password);
    await usermanagement.clickCreateUserAccount();
    await usermanagement.clickDone();
});
test('Test onboarding Instructor',async({page})=>{
    const poManager=new POManager(page);
    const adminDashBoard=poManager.getAdminDashBoard(); 
    const usermanagement= poManager.getUserManagementPage();
    await adminDashBoard.clickUserManagementModule();
    await usermanagement.clickOnboardingTab();
    const email=faker.internet.email();
    await usermanagement.enterEmail(email);
    const firstName=faker.person.firstName();
    await usermanagement.enterFirstName(firstName);
    const lastName=faker.person.lastName();
    await usermanagement.enterLastName(lastName); 
    await usermanagement.selectRole(testdata.instructorrole);
    await usermanagement.selectDepartment('Engineering');
    await usermanagement.enterPassword(testdata.password);
    await usermanagement.clickCreateUserAccount();
    await usermanagement.clickDone();
});
test('Test Onboarding Learner',async({page})=>{
    const poManager=new POManager(page);
    const adminDashBoard=poManager.getAdminDashBoard(); 
    const usermanagement= poManager.getUserManagementPage();
    await adminDashBoard.clickUserManagementModule();
    await usermanagement.clickOnboardingTab();
    const email=faker.internet.email();
    await usermanagement.enterEmail(email);
    const firstName=faker.person.firstName();
    await usermanagement.enterFirstName(firstName);
    const lastName=faker.person.lastName();
    await usermanagement.enterLastName(lastName); 
    await usermanagement.selectRole(testdata.learnerrole);
    await usermanagement.selectDepartment('Engineering');
    await usermanagement.enterPassword(testdata.password);
    await usermanagement.clickCreateUserAccount();
    await usermanagement.clickDone();
});