const {test,expect} = require('@playwright/test');
const {POManager}=require('../PageObjects/POManager');
import { faker } from '@faker-js/faker';
const testdata=JSON.parse( JSON.stringify(require('../TestData/signInPageTestData.json')));

test.beforeEach(async({page})=>{
    const poManager=new POManager(page);
    const signinPage=poManager.getSigninPage();
    await signinPage.navigate(testdata.url);
    await signinPage.enterEmail(testdata.adminusername);
    await signinPage.enterPassword(testdata.password);
    await signinPage.clickSignin();
    await expect(page).toHaveURL("https://skill-assist.ai/QapitolQA/dashboard");
    //await page.waitForTimeout(5000);
});
test('Test Onboarding Admin',async({page})=>{
    const poManager=new POManager(page);
    const adminDashBoard=poManager.getAdminDashBoard();
    const usermanagement= poManager.getUserManagementPage();
    await adminDashBoard.clickUserManagementModule();
    await usermanagement.clickOnboardingTab();
    const email=faker.internet.email();
    await usermanagement.enterEmail(email);
    const firstName = faker.name.firstName();
    await usermanagement.enterFirstName(firstName);
   const lastName = faker.name.lastName();
    await usermanagement.enterLastName(lastName);
    await usermanagement.selectRole(testdata.adminrole);
    await usermanagement.selectDepartment('Engineering');
    await usermanagement.enterPassword(testdata.password);
    await usermanagement.clickCreateUserAccount();
    await usermanagement.clickDone();
});
test('Test onboarding Instructor',async({page})=>{
    const poManager=new POManager(page);
    const adminDashBoard=poManager.getAdminDashBoard(); 
    const usermanagement= poManager.getUserManagementPage();
    await adminDashBoard.clickUserManagementModule();
    await usermanagement.clickOnboardingTab();
    const email=faker.internet.email();
    await usermanagement.enterEmail(email);
    const firstName = faker.name.firstName();
    await usermanagement.enterFirstName(firstName);
    const lastName = faker.name.lastName();
    await usermanagement.enterLastName(lastName); 
    await usermanagement.selectRole(testdata.instructorrole);
    await usermanagement.selectDepartment('Engineering');
    await usermanagement.enterPassword(testdata.password);
    await usermanagement.clickCreateUserAccount();
    await usermanagement.clickDone();
});
test('Test Onboarding Learner,Create a job role and assign Job role to the Learner',async({page})=>{
    const poManager=new POManager(page);
    const adminDashBoard=poManager.getAdminDashBoard(); 
    const usermanagement= poManager.getUserManagementPage();
    const programmanagerPage = poManager.getProgramManagerPage();
    const learnerDashBoard = poManager.getLearnerdashBoard();
    await adminDashBoard.clickUserManagementModule();
    await usermanagement.clickOnboardingTab();
    const email=faker.internet.email();
    await usermanagement.enterEmail(email);
    const firstName=faker.name.firstName();
    await usermanagement.enterFirstName(firstName);
    const lastName = faker.name.lastName();
    await usermanagement.enterLastName(lastName); 
    await usermanagement.selectRole(testdata.learnerrole);
    await usermanagement.selectDepartment('Engineering');
    await usermanagement.enterPassword(testdata.password);
    await usermanagement.clickCreateUserAccount();
    await usermanagement.clickDone();
    const jobrole = `.PlaywrightJob${faker.datatype.number({ min: 100, max: 999 })}`;
    await usermanagement.createJobRole(jobrole);
    await usermanagement.assignJobRoleToUser(email,jobrole);
    await  programmanagerPage.clickBackButton();
    await adminDashBoard.logoutAsAdmin();
    const signinPage=poManager.getSigninPage();
    await signinPage.enterEmail(email);
    await signinPage.enterPassword(testdata.password);
    await signinPage.clickSignin();
    await learnerDashBoard.clickRolesTab();
    await page.waitForTimeout(2000);
    await learnerDashBoard.verifyJobRoleCardVisible(jobrole);
});
